services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - aiworkspace-network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./aiworkspace
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - aiworkspace-network
    volumes:
      - ./aiworkspace:/app

networks:
  aiworkspace-network:
    driver: bridge

volumes:
  mongodb_data: